disabled_rules: # rule identifiers to exclude from running
  - trailing_whitespace
  - notification_center_detachment
  - todo
  - implicit_return

opt_in_rules: # some rules are only opt-in
  - attributes
  - closure_end_indentation
  - closure_spacing
  - contains_over_first_not_nil
  - empty_count
  - empty_string
  - explicit_init
  - first_where
  - implicit_return
  - joined_default_parameter
  - literal_expression_end_indentation
  - operator_usage_whitespace

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
  - vendor
  - XCTemplates
  - Core/Common/Controls/MD5.swift
  - Core/Common/Extensions/CoreString+MD5.swift

comma: error
force_cast: warning
force_try: warning
return_arrow_whitespace: error

# parameterized rules are first parameterized as a warning level, then error level.  
line_length: 120
type_body_length:
  warning: 300
  error: 400
cyclomatic_complexity:
  ignores_case_statements: true
file_length:
  warning: 500
  error: 1000
function_body_length:
  warning: 50
  error: 80
identifier_name:
  excluded: # excluded via string array
    - x
    - y
    - z
    - id